---
- name: install apache
  become: true
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: install git
  become: true
  ansible.builtin.yum:
    name: "git"
    state: present

- name: clone a repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/anyanpee/Jenkins-CI-CD-Pipeline-for-DevOps-Tooling-Website.git
    dest: /tmp/tooling
    force: yes

- name: copy website files to apache directory
  become: true
  ansible.builtin.copy:
    src: /tmp/tooling/
    dest: /var/www/html/
    remote_src: yes

- name: Start service httpd, if not started
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: Enable httpd service
  become: true
  ansible.builtin.service:
    name: httpd
    enabled: yes
