---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
    
    - name: install additional monitoring tools
      yum:
        name:
          - tcpdump
          - nmap
          - htop
        state: latest
    
    - name: create wireshark config directory
      file:
        path: /etc/wireshark
        state: directory
        mode: '0755'

- name: update LB server
  hosts: lb
  become: yes
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
    
    - name: install additional monitoring tools
      apt:
        name:
          - tcpdump
          - nmap
          - htop
        state: latest
    
    - name: configure wireshark permissions
      lineinfile:
        path: /etc/group
        regexp: '^wireshark:'
        line: 'wireshark:x:1001:'
        create: yes
